import { PrismaClient } from "@prisma/client";

/**
 * Seeds the tradeable instruments across all asset classes (forex,
 * commodities, indices, crypto, stocks). User accounts are created through
 * the registration flow, not by the seed script.
 */
const prisma = new PrismaClient();

interface SeedInstrument {
  symbol: string;
  name: string;
  category: "FOREX" | "COMMODITY" | "INDEX" | "CRYPTO" | "STOCK";
  base: string;
  quote: string;
  digits: number;
  pipSize: string;
  pipValue: string;
  contractSize: string;
  marginPerLot: string;
  commissionPerLot: string;
  swapLongPips: string;
  swapShortPips: string;
  basePrice: string;
  feedSymbol: string;
}

const INSTRUMENTS: SeedInstrument[] = [
  // ── Forex ──────────────────────────────────────────────────────────────────
  {
    symbol: "AUDCAD",
    name: "Australian Dollar / Canadian Dollar",
    category: "FOREX",
    base: "AUD",
    quote: "CAD",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "7.4",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "0.89200",
    feedSymbol: "OANDA:AUD_CAD",
  },
  {
    symbol: "EURUSD",
    name: "Euro / US Dollar",
    category: "FOREX",
    base: "EUR",
    quote: "USD",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "10",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "1.08500",
    feedSymbol: "OANDA:EUR_USD",
  },
  {
    symbol: "GBPUSD",
    name: "British Pound / US Dollar",
    category: "FOREX",
    base: "GBP",
    quote: "USD",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "10",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "1.27400",
    feedSymbol: "OANDA:GBP_USD",
  },
  {
    symbol: "USDJPY",
    name: "US Dollar / Japanese Yen",
    category: "FOREX",
    base: "USD",
    quote: "JPY",
    digits: 3,
    pipSize: "0.01",
    pipValue: "9.1",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "149.500",
    feedSymbol: "OANDA:USD_JPY",
  },
  {
    symbol: "AUDUSD",
    name: "Australian Dollar / US Dollar",
    category: "FOREX",
    base: "AUD",
    quote: "USD",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "10",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "0.65800",
    feedSymbol: "OANDA:AUD_USD",
  },
  {
    symbol: "USDCAD",
    name: "US Dollar / Canadian Dollar",
    category: "FOREX",
    base: "USD",
    quote: "CAD",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "7.4",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "1.36200",
    feedSymbol: "OANDA:USD_CAD",
  },
  {
    symbol: "NZDUSD",
    name: "New Zealand Dollar / US Dollar",
    category: "FOREX",
    base: "NZD",
    quote: "USD",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "10",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "0.60800",
    feedSymbol: "OANDA:NZD_USD",
  },
  {
    symbol: "EURGBP",
    name: "Euro / British Pound",
    category: "FOREX",
    base: "EUR",
    quote: "GBP",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "12.7",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "0.85100",
    feedSymbol: "OANDA:EUR_GBP",
  },
  // ── Commodities ────────────────────────────────────────────────────────────
  {
    symbol: "XAUUSD",
    name: "Gold vs US Dollar",
    category: "COMMODITY",
    base: "XAU",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "1",
    contractSize: "100",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "2.5",
    swapShortPips: "1.2",
    basePrice: "2350.00",
    feedSymbol: "OANDA:XAU_USD",
  },
  {
    symbol: "XAGUSD",
    name: "Silver vs US Dollar",
    category: "COMMODITY",
    base: "XAG",
    quote: "USD",
    digits: 3,
    pipSize: "0.001",
    pipValue: "5",
    contractSize: "5000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "2.0",
    swapShortPips: "1.0",
    basePrice: "30.500",
    feedSymbol: "OANDA:XAG_USD",
  },
  {
    symbol: "WTIUSD",
    name: "Crude Oil WTI",
    category: "COMMODITY",
    base: "WTI",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "1",
    contractSize: "1000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.8",
    swapShortPips: "0.9",
    basePrice: "78.50",
    feedSymbol: "OANDA:WTI_USD",
  },
  // ── Indices ────────────────────────────────────────────────────────────────
  {
    symbol: "US30",
    name: "Dow Jones 30",
    category: "INDEX",
    base: "US30",
    quote: "USD",
    digits: 1,
    pipSize: "1",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.5",
    swapShortPips: "0.5",
    basePrice: "38500.0",
    feedSymbol: "DIA",
  },
  {
    symbol: "NAS100",
    name: "Nasdaq 100",
    category: "INDEX",
    base: "NAS100",
    quote: "USD",
    digits: 1,
    pipSize: "1",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.5",
    swapShortPips: "0.5",
    basePrice: "17800.0",
    feedSymbol: "QQQ",
  },
  {
    symbol: "SPX500",
    name: "S&P 500",
    category: "INDEX",
    base: "SPX500",
    quote: "USD",
    digits: 1,
    pipSize: "0.1",
    pipValue: "50",
    contractSize: "10",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.5",
    swapShortPips: "0.5",
    basePrice: "5450.0",
    feedSymbol: "SPY",
  },
  // ── Crypto ─────────────────────────────────────────────────────────────────
  {
    symbol: "BTCUSD",
    name: "Bitcoin vs US Dollar",
    category: "CRYPTO",
    base: "BTC",
    quote: "USD",
    digits: 1,
    pipSize: "0.1",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "5.0",
    swapShortPips: "2.5",
    basePrice: "64000.0",
    feedSymbol: "BINANCE:BTCUSDT",
  },
  {
    symbol: "ETHUSD",
    name: "Ethereum vs US Dollar",
    category: "CRYPTO",
    base: "ETH",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "5.0",
    swapShortPips: "2.5",
    basePrice: "3200.00",
    feedSymbol: "BINANCE:ETHUSDT",
  },
  // ── More Forex (crosses + JPY + CHF) ───────────────────────────────────────
  {
    symbol: "USDCHF",
    name: "US Dollar / Swiss Franc",
    category: "FOREX",
    base: "USD",
    quote: "CHF",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "11.1",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "0.90200",
    feedSymbol: "OANDA:USD_CHF",
  },
  {
    symbol: "EURJPY",
    name: "Euro / Japanese Yen",
    category: "FOREX",
    base: "EUR",
    quote: "JPY",
    digits: 3,
    pipSize: "0.01",
    pipValue: "6.7",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "162.050",
    feedSymbol: "OANDA:EUR_JPY",
  },
  {
    symbol: "GBPJPY",
    name: "British Pound / Japanese Yen",
    category: "FOREX",
    base: "GBP",
    quote: "JPY",
    digits: 3,
    pipSize: "0.01",
    pipValue: "6.7",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "190.050",
    feedSymbol: "OANDA:GBP_JPY",
  },
  {
    symbol: "EURCHF",
    name: "Euro / Swiss Franc",
    category: "FOREX",
    base: "EUR",
    quote: "CHF",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "11.1",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "0.97900",
    feedSymbol: "OANDA:EUR_CHF",
  },
  {
    symbol: "EURAUD",
    name: "Euro / Australian Dollar",
    category: "FOREX",
    base: "EUR",
    quote: "AUD",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "6.6",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "1.64900",
    feedSymbol: "OANDA:EUR_AUD",
  },
  {
    symbol: "GBPCAD",
    name: "British Pound / Canadian Dollar",
    category: "FOREX",
    base: "GBP",
    quote: "CAD",
    digits: 5,
    pipSize: "0.0001",
    pipValue: "7.4",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "1.73600",
    feedSymbol: "OANDA:GBP_CAD",
  },
  {
    symbol: "CHFJPY",
    name: "Swiss Franc / Japanese Yen",
    category: "FOREX",
    base: "CHF",
    quote: "JPY",
    digits: 3,
    pipSize: "0.01",
    pipValue: "6.7",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "179.050",
    feedSymbol: "OANDA:CHF_JPY",
  },
  {
    symbol: "AUDJPY",
    name: "Australian Dollar / Japanese Yen",
    category: "FOREX",
    base: "AUD",
    quote: "JPY",
    digits: 3,
    pipSize: "0.01",
    pipValue: "6.7",
    contractSize: "100000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "3.2",
    swapShortPips: "1.8",
    basePrice: "98.300",
    feedSymbol: "OANDA:AUD_JPY",
  },
  // ── More Commodities ────────────────────────────────────────────────────────
  {
    symbol: "XBRUSD",
    name: "Brent Crude Oil",
    category: "COMMODITY",
    base: "XBR",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "1",
    contractSize: "1000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.8",
    swapShortPips: "0.9",
    basePrice: "82.50",
    feedSymbol: "OANDA:BCO_USD",
  },
  {
    symbol: "XPTUSD",
    name: "Platinum vs US Dollar",
    category: "COMMODITY",
    base: "XPT",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "5",
    contractSize: "500",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "2.0",
    swapShortPips: "1.0",
    basePrice: "985.00",
    feedSymbol: "OANDA:XPT_USD",
  },
  {
    symbol: "XPDUSD",
    name: "Palladium vs US Dollar",
    category: "COMMODITY",
    base: "XPD",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "5",
    contractSize: "500",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "2.0",
    swapShortPips: "1.0",
    basePrice: "950.00",
    feedSymbol: "OANDA:XPD_USD",
  },
  {
    symbol: "NGUSD",
    name: "Natural Gas",
    category: "COMMODITY",
    base: "NG",
    quote: "USD",
    digits: 3,
    pipSize: "0.001",
    pipValue: "10",
    contractSize: "10000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.5",
    swapShortPips: "0.8",
    basePrice: "2.150",
    feedSymbol: "OANDA:NATGAS_USD",
  },
  {
    symbol: "HGUSD",
    name: "Copper",
    category: "COMMODITY",
    base: "HG",
    quote: "USD",
    digits: 3,
    pipSize: "0.001",
    pipValue: "25",
    contractSize: "25000",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.5",
    swapShortPips: "0.8",
    basePrice: "4.150",
    feedSymbol: "OANDA:XCU_USD",
  },
  // ── More Indices (European + Asian) ─────────────────────────────────────────
  {
    symbol: "GER40",
    name: "DAX 40 (Germany 40)",
    category: "INDEX",
    base: "GER40",
    quote: "EUR",
    digits: 1,
    pipSize: "0.1",
    pipValue: "25",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.5",
    swapShortPips: "0.5",
    basePrice: "18500.0",
    feedSymbol: "OANDA:DE40_EUR",
  },
  {
    symbol: "UK100",
    name: "FTSE 100 (UK 100)",
    category: "INDEX",
    base: "UK100",
    quote: "GBP",
    digits: 1,
    pipSize: "0.1",
    pipValue: "25",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.5",
    swapShortPips: "0.5",
    basePrice: "8200.0",
    feedSymbol: "OANDA:UK100_GBP",
  },
  {
    symbol: "FRA40",
    name: "CAC 40 (France 40)",
    category: "INDEX",
    base: "FRA40",
    quote: "EUR",
    digits: 1,
    pipSize: "0.1",
    pipValue: "25",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.5",
    swapShortPips: "0.5",
    basePrice: "7600.0",
    feedSymbol: "OANDA:FR40_EUR",
  },
  {
    symbol: "JPN225",
    name: "Nikkei 225 (Japan 225)",
    category: "INDEX",
    base: "JPN225",
    quote: "JPY",
    digits: 1,
    pipSize: "0.1",
    pipValue: "25",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.5",
    swapShortPips: "0.5",
    basePrice: "39500.0",
    feedSymbol: "OANDA:JP225_USD",
  },
  {
    symbol: "VIX",
    name: "Volatility Index (VIX)",
    category: "INDEX",
    base: "VIX",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "100",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "1.5",
    swapShortPips: "0.5",
    basePrice: "13.50",
    feedSymbol: "OANDA:VIX_USD",
  },
  // ── More Crypto ─────────────────────────────────────────────────────────────
  {
    symbol: "SOLUSD",
    name: "Solana vs US Dollar",
    category: "CRYPTO",
    base: "SOL",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "5.0",
    swapShortPips: "2.5",
    basePrice: "145.00",
    feedSymbol: "BINANCE:SOLUSDT",
  },
  {
    symbol: "XRPUSD",
    name: "Ripple vs US Dollar",
    category: "CRYPTO",
    base: "XRP",
    quote: "USD",
    digits: 4,
    pipSize: "0.0001",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "5.0",
    swapShortPips: "2.5",
    basePrice: "0.5800",
    feedSymbol: "BINANCE:XRPUSDT",
  },
  {
    symbol: "ADAUSD",
    name: "Cardano vs US Dollar",
    category: "CRYPTO",
    base: "ADA",
    quote: "USD",
    digits: 4,
    pipSize: "0.0001",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "5.0",
    swapShortPips: "2.5",
    basePrice: "0.4200",
    feedSymbol: "BINANCE:ADAUSDT",
  },
  {
    symbol: "DOGEUSD",
    name: "Dogecoin vs US Dollar",
    category: "CRYPTO",
    base: "DOGE",
    quote: "USD",
    digits: 5,
    pipSize: "0.00001",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "5.0",
    swapShortPips: "2.5",
    basePrice: "0.12000",
    feedSymbol: "BINANCE:DOGEUSDT",
  },
  {
    symbol: "LINKUSD",
    name: "Chainlink vs US Dollar",
    category: "CRYPTO",
    base: "LINK",
    quote: "USD",
    digits: 3,
    pipSize: "0.001",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "5.0",
    swapShortPips: "2.5",
    basePrice: "14.500",
    feedSymbol: "BINANCE:LINKUSDT",
  },
  {
    symbol: "AVAXUSD",
    name: "Avalanche vs US Dollar",
    category: "CRYPTO",
    base: "AVAX",
    quote: "USD",
    digits: 3,
    pipSize: "0.001",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "5.0",
    swapShortPips: "2.5",
    basePrice: "28.500",
    feedSymbol: "BINANCE:AVAXUSDT",
  },
  {
    symbol: "MATICUSD",
    name: "Polygon vs US Dollar",
    category: "CRYPTO",
    base: "MATIC",
    quote: "USD",
    digits: 4,
    pipSize: "0.0001",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "1000",
    commissionPerLot: "7",
    swapLongPips: "5.0",
    swapShortPips: "2.5",
    basePrice: "0.5200",
    feedSymbol: "BINANCE:MATICUSDT",
  },
  // ── Stocks ────────────────────────────────────────────────────────────────
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    category: "STOCK",
    base: "AAPL",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "25",
    commissionPerLot: "1",
    swapLongPips: "0",
    swapShortPips: "0",
    basePrice: "210.00",
    feedSymbol: "AAPL",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    category: "STOCK",
    base: "MSFT",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "25",
    commissionPerLot: "1",
    swapLongPips: "0",
    swapShortPips: "0",
    basePrice: "505.00",
    feedSymbol: "MSFT",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    category: "STOCK",
    base: "NVDA",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "25",
    commissionPerLot: "1",
    swapLongPips: "0",
    swapShortPips: "0",
    basePrice: "170.00",
    feedSymbol: "NVDA",
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    category: "STOCK",
    base: "TSLA",
    quote: "USD",
    digits: 2,
    pipSize: "0.01",
    pipValue: "1",
    contractSize: "1",
    marginPerLot: "25",
    commissionPerLot: "1",
    swapLongPips: "0",
    swapShortPips: "0",
    basePrice: "330.00",
    feedSymbol: "TSLA",
  },
];

async function main() {
  console.log("🌱 Seeding instruments…");
  for (const i of INSTRUMENTS) {
    await prisma.instrument.upsert({
      where: { symbol: i.symbol },
      update: {
        name: i.name,
        category: i.category,
        base: i.base,
        quote: i.quote,
        digits: i.digits,
        pipSize: i.pipSize,
        pipValue: i.pipValue,
        contractSize: i.contractSize,
        marginPerLot: i.marginPerLot,
        commissionPerLot: i.commissionPerLot,
        swapLongPips: i.swapLongPips,
        swapShortPips: i.swapShortPips,
        basePrice: i.basePrice,
        feedSymbol: i.feedSymbol,
      },
      create: { ...i },
    });
    console.log(`  ✓ ${i.symbol}`);
  }

  console.log("✅ Seed complete.");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
