#!/usr/bin/env bash
# Renders deploy/Caddyfile.rendered from the production env file — one Caddy
# site block per NON-EMPTY domain variable. Caddy cannot skip a site block
# whose {$VAR} placeholder substitutes to an empty string (it becomes a
# keyless "global" block and the config fails to load), so optional brand
# domains are filtered out here instead. deploy.sh runs this before compose.
#
# Adding a brand is still env-only: set DOMAIN_N/TRADE_DOMAIN_N in
# .env.production and redeploy — this script picks them up automatically.
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${1:-$ROOT/.env.production}"
[[ -f "$ENV_FILE" ]] || { echo "Missing $ENV_FILE" >&2; exit 1; }

env_value() {
  grep -E "^$1=" "$ENV_FILE" | tail -1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//' | tr -d '[:space:]'
}

email="$(env_value CADDY_EMAIL)"
[[ -n "$email" ]] || { echo "CADDY_EMAIL is not set in $ENV_FILE" >&2; exit 1; }

out="$ROOT/deploy/Caddyfile.rendered"
# Docker bind-mounts turn a missing file into an empty DIRECTORY at this
# path (raw `compose up` before the first render) — caddy then fails to read
# it. Remove that trap before writing.
if [[ -d "$out" ]]; then
  echo "Removing stale directory at $out (Docker bind-mount artifact)…" >&2
  rm -rf "$out"
fi
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  printf '# Generated by deploy/render-caddy.sh from %s — do not edit.\n' "$(basename "$ENV_FILE")"
  printf '{\n  email %s\n  admin off\n}\n\n' "$email"
  cat <<'SNIPPET'
# Shared site configuration — every domain block below imports this, so all
# brand families get identical proxying, security headers, health checks, and
# logging.
(app-site) {
  encode zstd gzip
  header {
    Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options "nosniff"
    Referrer-Policy "strict-origin-when-cross-origin"
    -Server
  }
  reverse_proxy app:3000 {
    health_uri /api/health
    health_interval 15s
    health_timeout 5s
  }
  log {
    output stdout
    format json
  }
}

SNIPPET
  for var in DOMAIN TRADE_DOMAIN DOMAIN_2 TRADE_DOMAIN_2 DOMAIN_3 TRADE_DOMAIN_3; do
    value="$(env_value "$var")"
    if [[ -n "$value" ]]; then
      printf '# %s\n%s {\n  import app-site\n}\n\n' "$var" "$value"
      # www → apex canonical redirect for apex domains (subdomains skip it:
      # www.trade.* is never advertised). Caddy provisions www TLS itself.
      if [[ "$value" != *.*.* ]]; then
        printf '# www → %s\nwww.%s {\n  redir https://%s{uri} permanent\n}\n\n' "$value" "$value" "$value"
      fi
    fi
  done
} > "$tmp"
mv "$tmp" "$out"

sites="$(grep -c 'import app-site' "$out")"
echo "Rendered $out — $sites active site block(s)."
